# Generated by Django 5.2.5 on 2025-08-24 06:58

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=150, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=15, null=True, region='UZ')),
                ('telegram_username', models.URLField(blank=True, db_index=True, max_length=264, null=True)),
                ('section', models.CharField(blank=True, choices=[('film', 'Film'), ('technical', 'Technical')], db_index=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
