# Generated by Django 5.2.5 on 2025-09-12 16:37

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Full name of the contact person', max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address of the contact person', max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Phone number of the contact person', max_length=20, null=True, region='UZ')),
                ('telegram_username', models.CharField(blank=True, db_index=True, help_text='Telegram username of the contact person', max_length=64, null=True)),
                ('section', models.CharField(blank=True, choices=[('film', 'Film'), ('technical', 'Technical')], db_index=True, help_text='Section category of the contact', max_length=20, null=True)),
                ('subject', models.CharField(blank=True, db_index=True, help_text='Subject of the contact message', max_length=150, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, help_text='Message from the contact person', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='contact_con_name_6f2ef5_idx'), models.Index(fields=['email'], name='contact_con_email_2ebc86_idx'), models.Index(fields=['phone_number'], name='contact_con_phone_n_fd38a4_idx'), models.Index(fields=['telegram_username'], name='contact_con_telegra_a100cd_idx'), models.Index(fields=['section'], name='contact_con_section_514db3_idx'), models.Index(fields=['subject'], name='contact_con_subject_968400_idx'), models.Index(fields=['created_at'], name='contact_con_created_eb2247_idx')],
            },
        ),
    ]
