# Generated by Django 5.2.5 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telegram_username',
            field=models.URLField(blank=True, db_index=True, max_length=264, null=True),
        ),
    ]
