# Generated by Django 5.2.5 on 2025-08-31 06:42

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_email_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address of the contact person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Message from the contact person', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, help_text='Full name of the contact person', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Phone number of the contact person', max_length=20, null=True, region='UZ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='section',
            field=models.CharField(blank=True, choices=[('film', 'Film'), ('technical', 'Technical')], db_index=True, help_text='Section category of the contact', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, db_index=True, help_text='Subject of the contact message', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram username of the contact person', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='contact_con_name_6f2ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contact_con_email_2ebc86_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone_number'], name='contact_con_phone_n_fd38a4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['telegram_username'], name='contact_con_telegra_a100cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['section'], name='contact_con_section_514db3_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['subject'], name='contact_con_subject_968400_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='contact_con_created_eb2247_idx'),
        ),
    ]
