# Generated by Django 5.2.5 on 2025-08-24 06:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=350, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=450, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='films')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('trailer_link', models.URLField(blank=True, max_length=300, null=True, unique=True)),
                ('bot_link', models.URLField(blank=True, max_length=300, null=True)),
                ('bot_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('UZ', 'Uzbek')], default='UZ', max_length=50)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('age_limit', models.CharField(default='0', max_length=3)),
                ('views', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_category', to='category.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_country', to='film.country')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='film.film')),
            ],
        ),
    ]
