# Generated by Django 5.2.5 on 2025-09-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(help_text='The user who reacted to the film', on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ForeignKey(help_text='The film that was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film.film'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['name'], name='film_film_name_d3563e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['year'], name='film_film_year_b81e97_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['release_date'], name='film_film_release_28071f_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['slug'], name='film_film_slug_b81a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['category'], name='film_film_categor_4d9446_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['country'], name='film_film_country_022f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['trailer_link'], name='film_film_trailer_d7b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['bot_link'], name='film_film_bot_lin_9d2ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['bot_code'], name='film_film_bot_cod_bf4427_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['language'], name='film_film_languag_16bd90_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['duration'], name='film_film_duratio_adf9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['age_type'], name='film_film_age_typ_6bba91_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['views'], name='film_film_views_3a0127_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['p'], name='film_film_p_55720c_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['film'], name='film_reacti_film_id_716a00_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user'], name='film_reacti_user_id_d3a624_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['reaction'], name='film_reacti_reactio_1f7ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['created_at'], name='film_reacti_created_8507de_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_film_reaction'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='film_review_user_id_54e798_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['film'], name='film_review_film_id_11802c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='film_review_created_8ead47_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['updated_at'], name='film_review_updated_1f5683_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_film_review'),
        ),
    ]
