# Generated by Django 5.2.5 on 2025-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='film_tags', to='category.tag'),
        ),
    ]
