# Generated by Django 5.2.5 on 2025-09-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_film_review',
        ),
    ]
