# Generated by Django 5.2.5 on 2025-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_limit',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0),
        ),
    ]
