# Generated by Django 5.2.5 on 2025-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_film_age_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='age_limit',
            new_name='age_type',
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('UZ', 'Uzbek')], default='UZ', max_length=2),
        ),
    ]
