# Generated by Django 5.2.5 on 2025-08-26 02:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_rename_age_limit_film_age_type_alter_film_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Write your review about the film', null=True, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(help_text='The film that was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film.film', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the review was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='film_review_user_id_54e798_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['film'], name='film_review_film_id_11802c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='film_review_created_593f0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_film_review'),
        ),
    ]
