# Generated by Django 5.2.5 on 2025-08-26 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_alter_review_options_alter_review_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the reaction was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='film',
            field=models.ForeignKey(help_text='The film that the user reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='film.film', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], help_text="User's reaction to the film (like or dislike)", verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(help_text='The user who reacted to the film', on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['film'], name='film_reacti_film_id_716a00_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user'], name='film_reacti_user_id_d3a624_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['reaction'], name='film_reacti_reactio_1f7ce7_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_film_reaction'),
        ),
    ]
