# Generated by Django 5.2.5 on 2025-08-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_alter_reaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, help_text='The ISO 3166-1 alpha-3 country code (e.g., UZB)', max_length=3, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this country was added', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, help_text='The official name of the country (e.g., Uzbekistan)', max_length=150, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this country was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='film_countr_name_360ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='film_countr_code_03b22c_idx'),
        ),
    ]
