# Generated by Django 5.2.5 on 2025-08-31 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_country_code_alter_country_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='film_review_created_593f0d_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the review was created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time when the review was last updated'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='film_review_created_8ead47_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['updated_at'], name='film_review_updated_1f5683_idx'),
        ),
    ]
