# Generated by Django 5.2.5 on 2025-08-31 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_remove_review_film_review_created_593f0d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this country was added'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time when this country was last updated'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the reaction was created'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], db_index=True, help_text="User's reaction to the film (like or dislike)"),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['created_at'], name='film_countr_created_e87513_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['updated_at'], name='film_countr_updated_04c301_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['created_at'], name='film_reacti_created_8507de_idx'),
        ),
    ]
