# Generated by Django 5.2.5 on 2025-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_name_alter_category_parent_and_more'),
        ('film', '0011_alter_country_created_at_alter_country_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_type',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], db_index=True, default=0, help_text='Minimum recommended viewer age'),
        ),
        migrations.AlterField(
            model_name='film',
            name='bot_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique bot access code for the film', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='bot_link',
            field=models.URLField(blank=True, db_index=True, help_text='Telegram bot link to access the film', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(blank=True, db_index=True, help_text='Film duration in HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('UZ', 'Uzbek')], db_index=True, default='UZ', help_text='Main language of the film', max_length=2),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the film was added to the system'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_link',
            field=models.URLField(blank=True, db_index=True, help_text='YouTube or other video platform trailer URL', max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total number of views'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The year the film was released', null=True),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['slug'], name='film_film_slug_b81a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['category'], name='film_film_categor_4d9446_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['country'], name='film_film_country_022f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['trailer_link'], name='film_film_trailer_d7b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['bot_link'], name='film_film_bot_lin_9d2ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['bot_code'], name='film_film_bot_cod_bf4427_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['language'], name='film_film_languag_16bd90_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['duration'], name='film_film_duratio_adf9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['age_type'], name='film_film_age_typ_6bba91_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['views'], name='film_film_views_3a0127_idx'),
        ),
    ]
