# Generated by Django 5.2.5 on 2025-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_name_alter_category_parent_and_more'),
        ('film', '0012_alter_film_age_type_alter_film_bot_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='p',
            field=models.IntegerField(choices=[(0, '240p'), (1, '360p'), (2, '480p'), (3, '720p'), (4, '1080p'), (5, '4K')], db_index=True, default=2, help_text='Video quality of the film'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['p'], name='film_film_p_55720c_idx'),
        ),
    ]
