# Generated by Django 5.2.5 on 2025-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_customuser_birth_date_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, help_text='Enter your birth date', null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_name'], name='users_custo_first_n_4c3095_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_name'], name='users_custo_last_na_5b53f3_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='users_custo_date_jo_3d5338_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['gender'], name='users_custo_gender_a6b677_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['birth_date'], name='users_custo_birth_d_54f6b2_idx'),
        ),
    ]
