# Generated by Django 5.2.5 on 2025-08-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_rename_age_limit_film_age_type_alter_film_language'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the wishlist was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the movie was added to the wishlist', verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='movie',
            field=models.ForeignKey(help_text='The movie added to the wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='film.film', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(help_text='The wishlist this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='wishlist.wishlist', verbose_name='Wishlist'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='wishlist_wi_user_id_ec8321_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist'], name='wishlist_wi_wishlis_cf7a15_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['movie'], name='wishlist_wi_movie_i_65e6e1_idx'),
        ),
    ]
