# Generated by Django 5.2.5 on 2025-08-26 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_country_code_alter_country_created_at_and_more'),
        ('wishlist', '0002_alter_wishlist_options_alter_wishlistitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the wishlist was created'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the movie was added to the wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='movie',
            field=models.ForeignKey(help_text='The movie added to the wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='film.film'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(help_text='The wishlist this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='wishlist.wishlist'),
        ),
    ]
