# Generated by Django 5.2.5 on 2025-08-31 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_country_code_alter_country_created_at_and_more'),
        ('wishlist', '0003_alter_wishlist_created_at_alter_wishlist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the wishlist was created'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the movie was added to the wishlist'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='wishlist_wi_created_7481f7_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['added_at'], name='wishlist_wi_added_a_1c2b5a_idx'),
        ),
    ]
